# Generated by Django 5.0.5 on 2024-05-23 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='введите заголовок', max_length=128, verbose_name='заголовок')),
                ('content', models.TextField(help_text='введите содержимое статьи', verbose_name='содержимое статьи')),
                ('image', models.ImageField(blank=True, help_text='загрузите изображение', null=True, upload_to='blog_entries', verbose_name='изображение')),
                ('created_at', models.DateField(blank=True, help_text='заполните дату создания', null=True, verbose_name='дата создания')),
                ('is_published', models.BooleanField(default=False)),
                ('slug', models.CharField(blank=True, max_length=150, null=True, verbose_name='slug')),
                ('count_of_views', models.IntegerField(default=0, help_text='отображается количество просмотров', verbose_name='количество просмотров')),
            ],
            options={
                'verbose_name': 'записи блога',
                'verbose_name_plural': 'записи блога',
                'ordering': ['created_at'],
            },
        ),
    ]
