# Generated by Django 5.0.5 on 2024-05-23 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_edit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
