# Generated by Django 5.0.6 on 2024-05-07 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category_name",
                    models.CharField(
                        help_text="введите наименование категории",
                        max_length=128,
                        verbose_name="наименование категории",
                    ),
                ),
                (
                    "category_description",
                    models.CharField(
                        blank=True,
                        help_text="введите описание категории",
                        max_length=256,
                        null=True,
                        verbose_name="описание категории",
                    ),
                ),
            ],
            options={
                "verbose_name": "Категории",
                "verbose_name_plural": "Категории",
                "ordering": ["category_name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_name",
                    models.CharField(
                        help_text="введите наименование продукта",
                        max_length=128,
                        verbose_name="наименование продукта",
                    ),
                ),
                (
                    "product_description",
                    models.CharField(
                        help_text="введите описание продукта",
                        max_length=256,
                        verbose_name="описание продукта",
                    ),
                ),
                (
                    "product_image",
                    models.ImageField(
                        blank=True,
                        help_text="загрузите изображение продукта",
                        null=True,
                        upload_to="products/images/",
                        verbose_name="изображение",
                    ),
                ),
                (
                    "product_created_at",
                    models.DateField(
                        blank=True,
                        help_text="заполните дату создания",
                        null=True,
                        verbose_name="дата создания",
                    ),
                ),
                (
                    "product_updated_at",
                    models.DateField(
                        blank=True,
                        help_text="заполните дату изменения",
                        null=True,
                        verbose_name="дата последнего изменения",
                    ),
                ),
                (
                    "product_pay_for_sail",
                    models.CharField(
                        help_text="введите стоимость покупки",
                        max_length=128,
                        verbose_name="стоимость покупки",
                    ),
                ),
                (
                    "product_category",
                    models.ForeignKey(
                        blank=True,
                        help_text="введите категорию продукта",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="catalog.category",
                        verbose_name="категория продукта",
                    ),
                ),
            ],
            options={
                "verbose_name": "Продукты",
                "verbose_name_plural": "Продукты",
                "ordering": ["product_name"],
            },
        ),
    ]
