# Generated by Django 5.0.6 on 2024-05-07 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_product_product_pay_for_sail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="product_image",
            field=models.ImageField(
                blank=True,
                help_text="загрузите изображение продукта",
                null=True,
                upload_to="products",
                verbose_name="изображение",
            ),
        ),
    ]
