# Generated by Django 5.0.6 on 2024-06-04 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_version"),
    ]

    operations = [
        migrations.AlterField(
            model_name="version",
            name="version_name",
            field=models.CharField(
                blank=True,
                help_text="введите наименование версии",
                max_length=50,
                null=True,
                verbose_name="название версии",
            ),
        ),
    ]
