# Generated by Django 4.2.2 on 2024-06-20 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0008_remove_product_is_published"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_published",
            field=models.BooleanField(
                default=False, help_text="опубликовано", verbose_name="опубликовано"
            ),
        ),
    ]
